### ISSUE TITLE
Symlink fails, thinks there already is one made

### ISSUE THREAD

**Issue by themaster567** [leycec/kiseki-linux#5]
Hey there, having an issue with this script where it basically fails at the first juncture when it tries to symlink the bin file as it believes that one has already been made. I did try using the other TitS script (the one that doesn't include mods) first, which repeatedly failed at last step where it's supposed to launch the config tool, but I'm not sure if that would affect this at all. 

Is there anything you would like me to provide to help nail this down?

**Comment by leycec** [comment]
**Ohnoes.** Coincidentally, I've *almost* just completed TitS:FC using this exact installer (*...mind-blown during that grand finale, of course – like surely the most wtf-tier JRPG cliffhanger of all time*) and am on the precipice of doctoring up a TitS:SC **+** Evo Voices Lutris installer to continue getting my fix.

So, this is vitally relevant to my interests. By inspecting our `sora-no-kiseki-fc-gog-voiced.yml` script a second ago, I believe I see exactly what you mean. This, right:

```yml
        #FIXME: Remove this *AFTER* Lutris implicitly supports multi-part GOG
        #installers again. See above for voluminous commentary.
        - execute:
            description: Symlinking installer .bin slice into executable directory...
            command: ln -s "${gog_bin}" "$(dirname "${gog_exe}")/"
```

*...yah.* I absolutely see how that could cause issues when the `.bin` file resides in the same directory as the `.exe` file. In fact, that's terrible. What was I thinking here, people!?!? Further evidence we're on the BAD END historical timeline.

I'll repair this ASAP for everyone. Thanks so much for the quick heads up, @themaster567! Akita dog approves. :dog:
